### ISSUE TITLE
Make service setup optional

### ISSUE THREAD

**Issue by jessereynolds** [GeoffWilliams/puppet-puppet_nonroot#3]
It'd be good to have a parameter manage_service or some such so that the service setup can be optionally not managed. 

Use case: you want to be able to remotely trigger puppet runs of the nonroot agents. One way to do this (kind of horrible I agree) is it create execs to run each nonroot agent. If you do this, you don't want a separate service for each nonroot agent, as they could end up trying to run at the same time and one of them will lose and log an error.

**Comment by GeoffWilliams** [comment]
fixed in 0.2.0
